MAGECLOUD-3967: Add static and unit tests to magento-cloud-components
magento/magento-cloud-components pull request #11
Opened 2019-09-27 19:17 UTC by oshmyheliuk

2019-10-01 15:19 UTC, shiftedreality requested changes

2019-10-01 15:19 UTC, shiftedreality commented on .travis.yml
> +  - composer require "magento/framework:*" --no-update
This will fail without keys, don't you want to add if statement?

2019-10-01 15:19 UTC, shiftedreality commented on composer.json
> +    "phpcs": "phpcs ./ --standard=Test/static/phpcs-ruleset.xml -p -n",
Let's add Sniffs from ECE-Tools

2019-10-01 15:19 UTC, shiftedreality commented on .travis.yml
> +    - TEST_SUITE=static-unit XDEBUG=true
Yo don't need matrix, having only 1 variation

2019-10-01 15:43 UTC, oshmyheliuk commented on .travis.yml
> +  - composer require "magento/framework:*" --no-update
It's ok if it will fail, without "magento/framework:*" package test scripts won't run anyway.

2019-10-01 16:01 UTC, NadiyaS commented on Model/UrlFixer.php
>              && strpos($url, '/magento/') !== false
I would also create task to core to fix this issue

2019-10-01 16:18 UTC, oshmyheliuk commented on composer.json
> +    "phpcs": "phpcs ./ --standard=Test/static/phpcs-ruleset.xml -p -n",
added

2019-10-01 16:22 UTC, oshmyheliuk commented on .travis.yml
> +    - TEST_SUITE=static-unit XDEBUG=true
updated

2019-10-01 17:37 UTC, NadiyaS approved these changes

2019-10-01 19:54 UTC, shiftedreality requested changes

2019-10-01 19:54 UTC, shiftedreality commented on .travis.yml
> +  - if [ "$TEST_SUITE" == "static-unit" ]; then ./Test/static/static-travis.sh; fi
This must be in `tests` directory

2019-10-04 14:20 UTC, oshmyheliuk commented on .travis.yml
> +  - if [ "$TEST_SUITE" == "static-unit" ]; then ./Test/static/static-travis.sh; fi
Why `must`? it will be strange to have `Test` and `tests` directories on one level.

2019-10-04 16:40 UTC, shiftedreality approved these changes

2019-10-07 15:16 UTC, merged