SWAT-430: Extended debugging information about cache & indexer invali…
magento/magento-cloud-components pull request #26
Opened 2020-05-28 22:23 UTC by Alkar778

…dation

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-components#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

2020-05-29 14:51 UTC, YPyltiai commented
@Alkar778 , builds look to be red. Please look into that once you have a chance.

2020-05-29 16:33 UTC, oshmyheliuk commented on Model/Observer/IndexerStateSaveAfter.php
> +     * Apply model save operation
Is this description correct?
Looks like this description doesn't represent what the function is doing.
The same for `CacheFlushAll::execute`

2020-05-29 16:33 UTC, oshmyheliuk commented on Model/Observer/CacheFlushAll.php
> +class CacheFlushAll implements ObserverInterface
Please add descriptions to all new classes.

2020-05-29 17:41 UTC, oshmyheliuk commented
@YPyltiai builds are red as this is PR from a forked repo.

2020-06-01 15:43 UTC, shiftedreality requested changes

2020-06-01 15:43 UTC, shiftedreality commented on Model/Logger/Handler/Debug.php
> +    public function isHandling(array $record)
This method seems not needed

2020-06-01 15:43 UTC, shiftedreality commented on Model/Observer/CacheFlushAll.php
> +     * @throws \Magento\Framework\Validator\Exception
Replace with `use` short usage

2020-06-01 15:44 UTC, oshmyheliuk commented
@Alkar778 please fix static errors:
You can run static tests locally via command `composer:test`
```
FILE: ...avis/build/magento/magento-cloud-components/Model/Logger/Handler/Debug.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 10 | ERROR | Missing doc comment for class Debug
--------------------------------------------------------------------------------
FILE: ...is/build/magento/magento-cloud-components/Model/Observer/CacheFlushAll.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 15 | ERROR | Missing doc comment for class CacheFlushAll
--------------------------------------------------------------------------------
FILE: .../magento/magento-cloud-components/Model/Observer/IndexerStateSaveAfter.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 17 | ERROR | Missing doc comment for class IndexerStateSaveAfter
--------------------------------------------------------------------------------
FILE: .../travis/build/magento/magento-cloud-components/Model/Indexation/Logger.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 14 | ERROR | Missing doc comment for class Logger
--------------------------------------------------------------------------------
```

2020-06-03 17:33 UTC, Alkar778 commented on Model/Observer/CacheFlushAll.php
> +class CacheFlushAll implements ObserverInterface
done

2020-06-03 17:33 UTC, Alkar778 commented on Model/Observer/IndexerStateSaveAfter.php
> +     * Apply model save operation
fixed

2020-06-03 17:34 UTC, Alkar778 commented on Model/Logger/Handler/Debug.php
> +    public function isHandling(array $record)
this method override parent behavior and log without conditions.
This class is using in di.xml

2020-06-03 20:29 UTC, oshmyheliuk commented
Test are green https://github.com/magento/magento-cloud-components/pull/27

2020-06-03 20:32 UTC, oshmyheliuk approved these changes

2020-06-03 20:59 UTC, shiftedreality approved these changes

2020-06-04 13:32 UTC, shiftedreality commented
@Alkar778 do you want us to QA this PR or you can make it with your team?

2020-06-04 21:12 UTC, Alkar778 commented
@shiftedreality 
I've already done a QA but it would be great if you will able to do QA as well.

2020-06-04 21:13 UTC, shiftedreality commented
@Alkar778 could you provide a testing scenario for our QA?

2020-06-05 00:13 UTC, Alkar778 commented
@shiftedreality 

Test scenario:
1. Install vanilla Magento with this module.
2. Run `php bin/magento setup:di:compile `
3. Run `php bin/magento indexer:reindex ` 
4. File `indexation.log` has been created in `var/log` directory with 14 records

5. Remove `var/log/indexation.log` and `var/log/cache.log`
6. Run `php bin/magento cache:flush`
7. File `cache.log` has been created in `var/log` directory with 2 records

8. Remove `var/log/cache.log`
9. Run `php bin/magento cache:clean`
10. File `cache.log` has been created in `var/log` directory with 19 records

2020-06-05 20:19 UTC, andriyShevtsov commented
QA approved

2020-06-05 20:32 UTC, oshmyheliuk approved these changes

2020-06-05 20:32 UTC, merged