Update pull request template with doc requirements
magento/magento-cloud-components pull request #28
Opened 2020-06-05 20:30 UTC by meker12

# Description

Add release note and documentation requirements to PR template

### Fixed Issues (if relevant)

n/a

### Manual testing scenarios
n/a

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

2020-06-05 20:34 UTC, shiftedreality requested changes

2020-06-05 20:34 UTC, shiftedreality commented on .github/PULL_REQUEST_TEMPLATE.md
> +    If relevant, please provide a list of fixed issues in the format magento/magento-cloud-docker#<issue_number>.
Please change to `magento-cloud-components`

2020-06-05 20:34 UTC, shiftedreality commented on .github/PULL_REQUEST_TEMPLATE.md
> -1. magento/magento-cloud-components#<issue_number>: Issue title
Please change to `magento-cloud-components`

2020-06-05 20:34 UTC, shiftedreality commented on .github/PULL_REQUEST_TEMPLATE.md
> +For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).
This must link to Cloud Components release notes

2020-06-09 15:16 UTC, andriyShevtsov submitted a review, later dismissed

2020-06-09 15:21 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> +    If relevant, please provide a list of fixed issues in the format magento/magento-cloud-docker#<issue_number>.
```suggestion
    If relevant, please provide a list of fixed issues in the format magento/magento-cloud-components#<issue_number>.
```

2020-06-09 15:21 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> +1. magento/magento-cloud-docker#<issue_number>: Issue title
```suggestion
1. magento/magento-cloud-components#<issue_number>: Issue title
```

2020-06-09 15:22 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> +For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).
Those release notes don
t have too many examples, but you are correct.

2020-06-09 15:22 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> +For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).
```suggestion
For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcc-release-notes.html).
```

2020-06-09 16:46 UTC, NadiyaS commented on .github/PULL_REQUEST_TEMPLATE.md
> +For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcc-release-notes.html).
[Magento Cloud **Docker** release notes] ->[Magento Cloud **Components** release notes]

2020-06-09 16:47 UTC, NadiyaS commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
Shouldn't it be `release notes and/or documentation` ? as not always both are required

2020-06-11 15:45 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> +For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcc-release-notes.html).
```suggestion
For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Component release notes](https://devdocs.magento.com/cloud/release-notes/mcc-release-notes.html).
```

2020-06-11 15:46 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
```suggestion
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes or documentation changes
```

2020-06-11 15:50 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes or documentation changes
```suggestion
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
```

2020-06-11 15:51 UTC, meker12 commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
Changed the wording a bit -- is it OK?

2020-06-11 15:52 UTC, shiftedreality approved these changes

2020-06-11 16:03 UTC, NadiyaS approved these changes

2020-06-11 16:54 UTC, merged