MCLOUD-6023: Investigate Redis scan keys eviction
magento/magento-cloud-components pull request #31
Opened 2020-06-23 14:36 UTC by shiftedreality

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-components#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Components release notes](https://devdocs.magento.com/cloud/release-notes/mcc-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages

2020-07-14 17:09 UTC, oshmyheliuk commented on Model/Cache/Evictor.php
> +                $cacheConfig['backend_options']['server'],
Looks like you should check if `$cacheConfig` array contains required keys?

2020-07-14 17:16 UTC, shiftedreality commented on Model/Cache/Evictor.php
> +                $cacheConfig['backend_options']['server'],
Added

2020-07-14 19:33 UTC, oshmyheliuk submitted a review, later dismissed

2020-07-14 20:07 UTC, bbatsche submitted a review, later dismissed

2020-07-14 20:18 UTC, kandy requested changes

2020-07-14 20:18 UTC, kandy commented on Model/Cache/Evictor.php
> +            $keys = $client->scan($iterator, '*', self::EVICTION_LIMIT);
EVICTION_LIMIT should be configurable
Also  instead of `*` should be \Cm_Cache_Backend_Redis::PREFIX_KEY .'*'

2020-07-14 20:18 UTC, kandy commented on Model/Cache/Evictor.php
> +            }
add configurable timeout here
see \Cm_Cache_Backend_Redis::_collectGarbage as example

2020-07-14 20:18 UTC, kandy commented on composer.json
> +    "sort-packages": true
Why you need it?

2020-07-14 20:27 UTC, shiftedreality commented on composer.json
> +    "sort-packages": true
We use it in all packages, small improvement

2020-07-15 16:05 UTC, shiftedreality commented on Model/Cache/Evictor.php
> +            $keys = $client->scan($iterator, '*', self::EVICTION_LIMIT);
Done

2020-07-15 16:11 UTC, shiftedreality commented on Model/Cache/Evictor.php
> +            }
Will be added on next iteration

2020-07-15 20:50 UTC, andriyShevtsov commented
QA approved

2020-07-15 20:53 UTC, kandy commented on Model/Cache/Evictor.php
> +            }
It pretty important thing. Redis is one-tread application, so if you do not put timeout between scans it can block other request for long time and cause timeouts of cache read/writes by application

2020-07-15 20:57 UTC, shiftedreality commented on Model/Cache/Evictor.php
> +            }
Ok, added 20000 as `_collectGarbage`

2020-07-15 20:58 UTC, kandy submitted a review, later dismissed

2020-07-15 20:59 UTC, bbatsche submitted a review, later dismissed

2020-07-15 21:01 UTC, bbatsche submitted a review, later dismissed

2020-07-15 21:16 UTC, oshmyheliuk approved these changes

2020-07-15 21:30 UTC, arhiopterecs approved these changes

2020-07-16 14:02 UTC, merged