Logging improvements
magento/magento-cloud-components pull request #40
Opened 2020-08-24 16:41 UTC by Alkar778

### Description

### Fixed Issues (if relevant)

1. magento/magento-cloud-components#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Components release notes](https://devdocs.magento.com/cloud/release-notes/mcc-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages

2020-08-24 16:48 UTC, BarnyShergold commented
@magento run all tests

2020-08-24 16:51 UTC, BarnyShergold requested changes
Add proper description, notes etc
Ensure Travis tests pass.

2020-08-24 16:59 UTC, Alkar778 commented
@BarnyShergold 
The description has been updated.
Travis is failing not through my fault

2020-08-24 17:15 UTC, kandy commented on Model/Cache/InvalidateLogger.php
> +                                    debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS),
Can I ask you to remove from Trace the lines contains classes that match patterns "Magento\ObjectManager" and "Abstract\w*$" to decries trace size even more?

2020-08-24 17:18 UTC, kandy commented on Model/Cache/InvalidateLogger.php
> +            foreach ($invalidateInfo['tags'] as $tag) {
Should we get trace only once even if multiple tags is matched?

2020-08-24 18:05 UTC, kandy requested changes
Please check  the comment

2020-08-24 20:34 UTC, Alkar778 commented on Model/Cache/InvalidateLogger.php
> +                                    debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS),
Not only the ObjectManager class has been removed from the trace.
Please take a look at a second commit.

2020-08-24 20:35 UTC, Alkar778 commented on Model/Cache/InvalidateLogger.php
> +            foreach ($invalidateInfo['tags'] as $tag) {
Yes, good catch. 
We need to log trace only once.

2020-08-24 20:35 UTC, kandy commented on Model/Cache/InvalidateLogger.php
> +                                    debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS),
Thanks
Even better than I proposed

2020-08-24 20:41 UTC, kandy submitted a review, later dismissed

2020-08-25 09:32 UTC, BarnyShergold approved these changes, later dismissed
Accepted that Travis is failing for unknown reasons

2020-08-25 16:26 UTC, oshmyheliuk commented
@Alkar778 I've created separate PR from this pr for test running and static tests failed
```
FILE: /home/travis/build/magento/magento-cloud-components/Model/DebugTrace.php
------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------
 6 | ERROR | [x] Missing strict_types declaration
------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------
FILE: ...is/build/magento/magento-cloud-components/Model/Cache/InvalidateLogger.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 78 | ERROR | Code must not contain multiple empty lines in a row; found 2
    |       | empty lines
--------------------------------------------------------------------------------
```
Please fix.

2020-08-25 16:56 UTC, Alkar778 commented
@oshmyheliuk 
code style fixed

2020-08-25 17:01 UTC, BarnyShergold commented on Model/DebugTrace.php
> +namespace Magento\CloudComponents\Model;
Need to add -
```suggestion
declare(strict_types=1);


```

2020-08-25 17:01 UTC, BarnyShergold commented on Model/DebugTrace.php
> +namespace Magento\CloudComponents\Model;
Need to add -

```suggestion
declare(strict_types=1);

namespace Magento\CloudComponents\Model;
```

2020-08-25 17:23 UTC, oshmyheliuk commented on Model/DebugTrace.php
> +namespace Magento\CloudComponents\Model;
Yes, still failing without `declare`
```
FILE: /home/travis/build/magento/magento-cloud-components/Model/DebugTrace.php
------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------
 6 | ERROR | [x] Missing strict_types declaration
------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------
```

2020-08-26 16:06 UTC, Alkar778 commented
@oshmyheliuk 
I've pushed additional commit. Please review

2020-08-26 18:49 UTC, oshmyheliuk commented
@Alkar778 Static tests are ok, but functional failed
```
 [Exception]                                                                                                    
  Notice: Undefined index: file in /app/vendor/magento/magento-cloud-components/Model/DebugTrace.php on line 65 
```

2020-08-26 18:52 UTC, oshmyheliuk commented on Model/DebugTrace.php
> +        foreach ($trace as $index => $line) {
Need to add validation if elements of array `$line` is set.
```
$line['function']
$line['class']
$line['file']
```

2020-08-26 19:43 UTC, Alkar778 commented on Model/DebugTrace.php
> +        foreach ($trace as $index => $line) {
It always set 
https://www.php.net/manual/ru/function.debug-backtrace.php

2020-08-26 19:44 UTC, Alkar778 commented on Model/DebugTrace.php
> +        foreach ($trace as $index => $line) {
How can I reproduce case when the **file** key undefined?

2020-08-26 19:47 UTC, oshmyheliuk commented on Model/DebugTrace.php
> +        foreach ($trace as $index => $line) {
Such error happening during `setup:install`.
https://travis-ci.com/github/magento/magento-cloud-components/jobs/378018983

2020-08-28 19:56 UTC, Alkar778 commented on Model/DebugTrace.php
> +        foreach ($trace as $index => $line) {
Fixed

2020-08-31 23:35 UTC, BarnyShergold approved these changes

2020-09-01 13:24 UTC, oshmyheliuk approved these changes

2020-09-01 13:25 UTC, oshmyheliuk approved these changes

2020-09-01 13:29 UTC, shiftedreality approved these changes

2020-09-01 18:17 UTC, andriyShevtsov commented
QA approved

2020-09-01 18:20 UTC, merged