Update README.md
magento/magento-cloud-components pull request #8
Opened 2019-08-15 15:29 UTC by YPyltiai

2019-08-15 15:29 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento-cloud-components?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-cloud-components?pullRequest=8) before we can accept your contribution.<br/>

2019-08-15 16:22 UTC, hguthrie reviewed
I'm sure you can take some of the suggestions from the Docker readme and apply them here, too.

2019-08-15 16:22 UTC, hguthrie commented on README.md
>  Magento Cloud Components is a Magento module, designed to extend core functionality to operate best in Cloud. This module will contain Cloud-specific functionality, which will mostly be used within [
```suggestion
Magento Cloud Components is a Magento module, designed to extend core functionality to operate best in Cloud. This module contains Cloud-specific functionality for use with the [ECE-Tools](https://github.com/magento/ece-tools) package.
```

2019-08-15 16:22 UTC, hguthrie commented on README.md
> +Magento Cloud Suite includes set of packages, designed to deploy and manage Magento Commerce installations.
```suggestion
The Magento Cloud Suite includes a set of packages designed to deploy and manage Magento Commerce installations.
```

2019-08-15 16:22 UTC, hguthrie commented on README.md
>  - [Cloud DevDocs](https://devdocs.magento.com/guides/v2.2/cloud/bk-cloud.html)
```suggestion
- [Magento Cloud Guide DevDocs](https://devdocs.magento.com/guides/v2.3/cloud/bk-cloud.html)
```

2019-08-15 16:22 UTC, hguthrie commented on README.md
> +- [Release Notes](https://github.com/magento/ece-tools/releases)
```suggestion
- [ECE-Tools Release Notes](https://github.com/magento/ece-tools/releases)
```

2019-08-16 18:11 UTC, meker12 requested changes

2019-08-16 18:11 UTC, meker12 commented on README.md
> +You can submit issues and pull requests to extend functionality or fix potential bugs. Improvements to Magento Cloud Components can include any development experience improvements, optimizations for
Style rules -- avoid use of "etc."  -- See https://developers.google.com/style/word-list#letter-E.

2019-08-16 18:11 UTC, meker12 commented on README.md
> +Magento Cloud Components is a Magento module, designed to extend core functionality to operate best in Cloud. This module contains Cloud-specific functionality for use with the [ECE-Tools](https://gi
```suggestion
The Magento Cloud Components module extends Magento Commerce core functionality for sites deployed on the Cloud platform.  This module contains cloud-specific functionality for use with the [ece-tools](https://github.com/magento/ece-tools) package.
```

2019-08-17 01:30 UTC, meker12 approved these changes
One very small suggestion to approve/commit.  Also -- A comment about use "site" vs. "store" in information about deploying Magento Commerce on the Cloud platform

2019-08-17 01:30 UTC, meker12 commented on README.md
> +## Contributing to Magento Cloud Components Code Base
```suggestion
## Contributing to the Magento Cloud Components Code Base
```

2019-08-17 01:30 UTC, meker12 commented on README.md
> +The Magento Cloud Components module extends Magento Commerce core functionality for sites deployed on the Cloud platform.  This module contains cloud-specific functionality for use with the [ece-tool
I noticed that in the documentation, we sometimes use "sites" ( _for sites deployed on the Cloud platform_), and sometimes "store": 
 
From the PR for the Docker readme:
```Magento Cloud Docker is a package—part of the [Magento Cloud Suite](#magento-cloud-suite)—designed to develop, test, and deploy your Magento Commerce store.```

We should try to be consistent to avoid confusion.   Which is preferred "site" or "store"–maybe it depends on the context.   If so, then when should we use "site" and when "store".

2019-08-17 01:32 UTC, meker12 commented on README.md
> +- [ECE-Tools Release Notes](https://github.com/magento/ece-tools/releases)
```suggestion
- [Release Notes for the ece-tools package](https://github.com/magento/ece-tools/releases)
```

2019-08-19 16:49 UTC, YPyltiai commented on README.md
> +The Magento Cloud Components module extends Magento Commerce core functionality for sites deployed on the Cloud platform.  This module contains cloud-specific functionality for use with the [ece-tool
These are the same in case of Magento. Every site (installation of Magento) is a store in 100% cases. I agree about consistency but we may leave it as is for now and fix globally later.

2019-08-19 18:09 UTC, merged